In [ ]:
# web URL - https://www.themoviedb.org/settings/api
# URL - https://developer.themoviedb.org/reference/trending-movies

In [ ]:
import requests

url = "https://api.themoviedb.org/3/trending/movie/day?api_key=52bc6c90c263cde3f8518a1c880c803c&language=en-US&page=2"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1MmJjNmM5MGMyNjNjZGUzZjg1MThhMWM4ODBjODAzYyIsIm5iZiI6MTczMDA5NzQzNC44NjgsInN1YiI6IjY3MWYzMTFhMjdiZDU3ZDkxZjYzMWJkNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.b57cbi3m0F-2IUC1o2XCqlS4J1rxEuRDI-HX_U7H0WI"
}

response = requests.get(url, headers=headers)

print(response.text)

json_data = response.json()


import pandas as pd

pd.DataFrame(json_data['results'])

{"page":2,"results":[{"adult":false,"backdrop_path":"/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg","id":1339713,"title":"Obsession","original_title":"Obsession","overview":"After breaking the mysterious \"One Wish Willow\" to win his crush's heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.","poster_path":"/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":126.7208,"release_date":"2026-05-13","softcore":false,"video":false,"vote_average":8.181,"vote_count":6088},{"adult":false,"backdrop_path":"/wZ9Me7OndzgBOEAa8nSBNPu3Sl4.jpg","id":1538497,"title":"Hexed","original_title":"Hexed","overview":"An impulsive and unconventional teenage girl named Billie discovers secret magical abilities which, once unleashed, hurtle her into a spectacle-filled journey out of suburbia and into a vast witch realm called Hexe. Forced to team up with her cautious mother, Alice, they uncover family mysteries that could change the world of witches forever.","poster_path":"/yykeYKbDBM9eUMJUucaaDo2mi1p.jpg","media_type":"movie","original_language":"en","genre_ids":[12,16,10751,14,35],"popularity":14.9144,"release_date":"2026-11-25","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/p40lmrdI4blcAPZQMTPaiy5v5Ym.jpg","id":1291595,"title":"Insidious: Out of the Further","original_title":"Insidious: Out of the Further","overview":"Gemma, a young mother raising her daughter in the house she grew up in, discovers she can travel into The Further, the purgatorial realm of lost souls at the heart of the Insidious universe. When something evil comes after her, Gemma discovers an ability that changes everything: she doesn't just enter The Further, she can bring what lives there back to the real world. Once the demons realize her power, our world becomes their playground.","poster_path":"/4tTrW9dXCByS5wt2pXVWb58zNjz.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":533.378,"release_date":"2026-08-19","softcore":false,"video":false,"vote_average":7.725,"vote_count":694},{"adult":false,"backdrop_path":"/yBDxqDB29kpH9VojTytjGWBgmdJ.jpg","id":1101412,"title":"Fall 2: Deadpoint","original_title":"Fall 2: Deadpoint","overview":"On a perilous climb across Thailand's Mount Kwan, two climbers become trapped thousands of feet above the ground, where vertigo-inducing heights, sheer exposure, and impossible odds turn every moment into a fight for survival.","poster_path":"/fgSm5ylwiXbIHn8UbUXDjk9RRu4.jpg","media_type":"movie","original_language":"en","genre_ids":[53],"popularity":301.2096,"release_date":"2026-09-01","softcore":false,"video":false,"vote_average":7.316,"vote_count":508},{"adult":false,"backdrop_path":"/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg","id":1083381,"title":"Backrooms","original_title":"Backrooms","overview":"A strange doorway appears in the basement of a furniture showroom.","poster_path":"/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg","media_type":"movie","original_language":"en","genre_ids":[27,9648,878],"popularity":81.0513,"release_date":"2026-05-27","softcore":false,"video":false,"vote_average":7.0,"vote_count":3715},{"adult":false,"backdrop_path":"/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg","id":1108427,"title":"Moana","original_title":"Moana","overview":"Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.","poster_path":"/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg","media_type":"movie","original_language":"en","genre_ids":[10751,14,35,12],"popularity":98.5732,"release_date":"2026-07-08","softcore":false,"video":false,"vote_average":7.5,"vote_count":901},{"adult":false,"backdrop_path":"/ckDLzhqHG40CoNUwQWrAvzCYRIe.jpg","id":1490214,"title":"The Sun Never Sets","original_title":"The Sun Never Sets","overview":"While on an unexpected break from her older, divorced boyfriend, a woman runs into her ex-partner, plunging her into a volatile love triangle that threatens to undo her life.","poster_path":"/hpzzGHyVN4nE0GzqoAu12ko6ER3.jpg","media_type":"movie","original_language":"en","genre_ids":[10749,18,35],"popularity":3.647,"release_date":"2026-08-28","softcore":false,"video":false,"vote_average":9.5,"vote_count":2},{"adult":false,"backdrop_path":"/E812GNXYQqjJwN0cVPY3icHpaj.jpg","id":192139,"title":"The Brink of War","original_title":"The Brink of War","overview":"President Ronald Reagan races against time to salvage a deal with Soviet leader Mikhail Gorbachev that could dismantle nuclear arsenals—or ignite disaster. With pressure mounting on all sides, every word spoken brings the world closer to peace... or destruction.","poster_path":"/vCIQeQ2ynVqEjIvtbOXGnKtcgAX.jpg","media_type":"movie","original_language":"en","genre_ids":[18,36],"popularity":10.3976,"release_date":"2026-08-13","softcore":false,"video":false,"vote_average":7.1,"vote_count":34},{"adult":false,"backdrop_path":"/4E5RVsSUG1A4Adwbqupu5w6kofZ.jpg","id":1375441,"title":"Primetime","original_title":"Primetime","overview":"In 2006, To Catch a Predator host Chris Hansen sets out to make television history. When a high stakes operation goes fatally wrong, his veneered dream of fame curdles into a nightmare of performative justice.","poster_path":"/lmrulvLbmaejTix1YaMxo1oGhH1.jpg","media_type":"movie","original_language":"en","genre_ids":[18,53],"popularity":45.5884,"release_date":"2026-09-23","softcore":false,"video":false,"vote_average":6.877,"vote_count":118},{"adult":false,"backdrop_path":"/qjTqY5coNiz6sVtPng40IzltsoN.jpg","id":1084244,"title":"Toy Story 5","original_title":"Toy Story 5","overview":"When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.","poster_path":"/sfQtVlIHljToOwYjhe21KPGzZWK.jpg","media_type":"movie","original_language":"en","genre_ids":[16,10751,35,12],"popularity":155.0431,"release_date":"2026-06-17","softcore":false,"video":false,"vote_average":8.286,"vote_count":2596},{"adult":false,"backdrop_path":"/mpB4pgtUcc7rCLxvlknzCbAQQEE.jpg","id":1742441,"title":"V/H/S/Mixtape","original_title":"V/H/S/Mixtape","overview":"V/H/S/MIXTAPE cranks the volume on horror with a blood-soaked collection of cursed music videos, terrifying performances, and found footage. Press play. Pray it stops.","poster_path":"/uS8yoiA6NfsuYeOTbVfpem8Ib9.jpg","media_type":"movie","original_language":"en","genre_ids":[27,10402],"popularity":113.4714,"release_date":"2026-10-09","softcore":false,"video":false,"vote_average":4.4,"vote_count":17},{"adult":false,"backdrop_path":"/pmPXXniQlb4EdYY0gVZO90rf54F.jpg","id":1284046,"title":"Onslaught","original_title":"Onslaught","overview":"When a rogue squad of genetically engineered super soldiers break loose in the desert, a badass Army sniper must unleash hell to protect her young daughter.","poster_path":"/cOGtvhc6Ij9KvzM6jZsfQyg0B0O.jpg","media_type":"movie","original_language":"en","genre_ids":[28,27,53],"popularity":137.5813,"release_date":"2026-09-02","softcore":false,"video":false,"vote_average":5.8,"vote_count":102},{"adult":false,"backdrop_path":"/sl5NJ1vtyhP9Vr88bB4blULsJYp.jpg","id":791523,"title":"Wildwood","original_title":"Wildwood","overview":"Prue and her classmate Curtis are drawn into a magical forest filled with enchanted creatures, loyal allies, and formidable adversaries as they embark on a desperate quest to rescue Prue’s abducted baby brother from a murder of crows led by a mysterious woman named Alexandra.","poster_path":"/snFM00mpNAfUzUtkdEW0uDEvXA0.jpg","media_type":"movie","original_language":"en","genre_ids":[16,12,14],"popularity":14.4084,"release_date":"2026-10-19","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/A42JE6WJDMsICN3NU6XkUyYEF5F.jpg","id":1282159,"title":"Let's Have Kids!","original_title":"Let's Have Kids!","overview":"Two best friends, Emma and Phoebe, decide to get pregnant simultaneously to navigate motherhood together, but their friendship is tested when only one of them conceives.","poster_path":"/ciHBHFWAUn9tXNpm5NfDOkcgcMx.jpg","media_type":"movie","original_language":"en","genre_ids":[35],"popularity":2.9187,"release_date":"2026-10-13","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/bicMU6xVD5deVyKP2azpyx7xkmH.jpg","id":1263337,"title":"Heart of the Beast","original_title":"Heart of the Beast","overview":"After a harrowing plane crash, Special Forces officer James Belmont and his combat dog, Odin, find themselves stranded deep in the Alaskan wilderness. Together, they are forced into a brutal fight for survival against the elements.","poster_path":"/1ApfSA8JTqeha3GTFEY8syV4auq.jpg","media_type":"movie","original_language":"en","genre_ids":[12,53],"popularity":86.038,"release_date":"2026-09-19","softcore":false,"video":false,"vote_average":7.431,"vote_count":283},{"adult":false,"backdrop_path":"/bDsmYvrzto7xrEwqDpLC3SPhn9A.jpg","id":1422041,"title":"LA BOLA NEGRA","original_title":"La bola negra","overview":"The intertwined lives of three men in three different eras, three lives intimately linked by sexuality and desire, pain, and legacy.","poster_path":"/dbpyc3Zo0m4E15XcQ7tTwlLBEtE.jpg","media_type":"movie","original_language":"es","genre_ids":[18,10752],"popularity":20.2544,"release_date":"2026-09-25","softcore":false,"video":false,"vote_average":8.4,"vote_count":63},{"adult":false,"backdrop_path":"/y0reRTsewsPh0ePtgvDeLIsb5Wk.jpg","id":977942,"title":"The Uprising","original_title":"The Uprising","overview":"As war and plague devastate 14th-century England, a humble peasant ignites a rebellion, uniting an army of commoners to defy the King’s might in a desperate fight for justice and survival.","poster_path":"/7TUl15TOsIvndKlgMWTtLgtEzZP.jpg","media_type":"movie","original_language":"en","genre_ids":[36,18,28],"popularity":113.5757,"release_date":"2026-09-10","softcore":false,"video":false,"vote_average":7.989,"vote_count":306},{"adult":false,"backdrop_path":"/oqrYIDH4tvfEzPe1yqT4jzmAWHQ.jpg","id":1381071,"title":"Godzilla Minus Zero","original_title":"ゴジラ-0.0","overview":"War reduced Japan to zero, and Godzilla plunged it into minus. Two years have passed since then, and the country has faced agonizing struggles to achieve recovery and finally reclaim its daily life. Just as humanity managed to cling to a hard-won peace, a new threat strikes, crushing hope in an instant.","poster_path":"/hSmIJluOJmTWvJs4d7kHRxjc8s8.jpg","media_type":"movie","original_language":"ja","genre_ids":[878,27,28],"popularity":20.0568,"release_date":"2026-11-03","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/3afHil7EVm655wO2NS6RHxuyicE.jpg","id":1433367,"title":"One Night Only","original_title":"One Night Only","overview":"Two love-starved strangers crash into each other on the one night of the year when single people are allowed to have sex.","poster_path":"/f1v8IcYcQggeq1N0unoMJMrzTd9.jpg","media_type":"movie","original_language":"en","genre_ids":[10749,35],"popularity":28.4928,"release_date":"2026-08-06","softcore":false,"video":false,"vote_average":6.418,"vote_count":201},{"adult":false,"backdrop_path":"/yT8EkAvEkJDFeAxK7s7HlIPELRT.jpg","id":1228834,"title":"The Fix","original_title":"The Fix","overview":"Disillusioned by the end of the war in Afghanistan, a group of disgraced, war-torn ex-CIA operatives set out to Tehran to take down a life-changing score.","poster_path":"/yopXjun3ICFfJci2ukcEzceZjUs.jpg","media_type":"movie","original_language":"en","genre_ids":[28,53],"popularity":282.5063,"release_date":"2026-09-10","softcore":false,"video":false,"vote_average":6.784,"vote_count":58}],"total_pages":500,"total_results":10000}

# Import page 1 to page 500 data

In [ ]:
import pandas as pd
import requests

final_data = pd.DataFrame()

YOUR_API_KEY =  '52bc6c90c263cde3f8518a1c880c803c'

for i in range(1, 501):

    url = f"https://api.themoviedb.org/3/trending/movie/day?api_key={YOUR_API_KEY}&language=en-US&page={i}"

    response = requests.get(url, headers=headers)
    
    json_data = response.json()

    df = pd.DataFrame(json_data["results"])

    final_data = pd.concat([final_data, df], ignore_index=True)

    print(i)

final_data

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count
0,False,/wE6syT1vv6W24iLGfhR4kQHnIDN.jpg,1302904,Practical Magic 2,Practical Magic 2,The Owens sisters must confront the dark curse...,/ogwQOLbCfncjvBhFb5l0OmQH8KC.jpg,movie,en,"[10749, 14, 35]",89.1126,2026-09-09,False,False,6.286,131
1,False,/ujUwzNV8ZkOzZonvhhHsc9KOKDf.jpg,1058424,Hope,호프,In the remote South Korean village of Hope Har...,/1n37BJchWHLiSYQkuFxe5KjB951.jpg,movie,ko,"[878, 9648, 28]",42.2970,2026-07-15,False,False,7.300,127
2,False,/ytoLEl5yDaxB8AtZ52uKWjaQ9ql.jpg,1514026,Buddy,Buddy,"A magical, singing orange unicorn holds his ca...",/1BdZbNvl1SfrrX8J9X5tQzN6Ivu.jpg,movie,en,"[27, 35, 14]",14.7618,2026-08-27,False,False,7.821,81
3,False,/tzoarEu7TsG959upiELyYPm5kO9.jpg,1236045,Animals,Animals,When the son of an L.A. mayoral candidate is k...,/iISM36voS1E8gX9BM0DVK0kgi3E.jpg,movie,en,"[53, 18]",260.5060,2026-10-09,False,False,7.400,305
4,False,/zDE9hd1SG9695YncbZGjSf7Z9Jk.jpg,1153576,Street Fighter,Street Fighter,"In 1993, estranged Street Fighters Ryu and Ken...",/dJPT2Uf12X6aFg8i5N67NTpIZ9t.jpg,movie,en,"[28, 14]",41.0928,2026-10-13,False,False,6.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,False,/fUcT8bcJD3SZsy84Z9QRP6kOS7v.jpg,911916,Spider-Man: Beyond the Spider-Verse,Spider-Man: Beyond the Spider-Verse,Hunted by Miguel O'Hara's Spider Society and b...,/9KAe39xqyZnv9J4W3DRGdQqX82h.jpg,movie,en,"[16, 28, 12, 878]",7.0589,2027-06-16,False,False,0.000,0
376,False,/ll4RxoN4PxVWeOfqwa6VKdMPiO.jpg,1421967,Violette,Changer l'Eau des Fleurs,"Violette Toussaint, a cemetery caretaker in a ...",/oCTRbUsPCACAWf799j8kXKvhmnk.jpg,movie,fr,[18],2.1210,2026-12-09,False,False,0.000,0
377,False,/hZVIwxi6kK4KnpVPEWwdhG0cMM5.jpg,1012148,Chapel,Chapel,A man becomes a suspect in a serial murder cas...,/94sIggRUBioP19m3vJQfV3lq6Z6.jpg,movie,en,"[9648, 53]",2.4585,2025-05-09,False,False,7.100,9
378,False,/5MUMB3aPEPEQPCIAaygXFUTWE9Y.jpg,454639,Masters of the Universe,Masters of the Universe,"After being separated for 15 years, the Sword ...",/oRuyGUHdoaQxWP3SDfafGkStxTC.jpg,movie,en,"[28, 14, 878]",39.0138,2026-06-03,False,False,7.100,2226
379,False,/aFO0i3bl4d6o0odPix8xgiVsIYT.jpg,1154730,La Gradiva,La Gradiva,"Amid the ancient ruins of Pompeii, a group of ...",/y6AkOgTEPM9nTJUOeyvHqlf6Bgp.jpg,movie,fr,[18],5.2058,2026-10-21,False,False,0.000,0

In [ ]:
df=final_data[['id', 'title', 'original_title', 'overview','adult','original_language', 'popularity', 'release_date', 'vote_average', 'vote_count']]
df

In [ ]:
# Save the data to CSV
df.to_csv("trending_movies.csv", index=False)

In [16]:

import pandas as pd
import requests
import time

# Create an empty DataFrame before the loop
final_data = pd.DataFrame()

YOUR_API_KEY = "52bc6c90c263cde3f8518a1c880c803c"

for i in range(1, 501):

    url = f"https://api.themoviedb.org/3/trending/movie/day?api_key={YOUR_API_KEY}&language=en-US&page={i}"

    headers = {
        "accept": "application/json",
        "Authorization": "Bearer YOUR_ACCESS_TOKEN"
    }

    response = requests.get(url, headers=headers, timeout=30)

    if response.status_code == 200:
        json_data = response.json()

        # Convert JSON results into a DataFrame
        df = pd.DataFrame(json_data["results"])

        # Append the current page's data
        final_data = pd.concat(
            [final_data, df],
            ignore_index=True
        )

        print(f"Page {i} completed | Total rows: {len(final_data)}")

    else:
        print(f"Page {i} failed: {response.status_code}")
        print(response.text)

    time.sleep(0.1)

# Display the final dataset
print(final_data.shape)
print(final_data.head())

# Save the data to CSV
final_data.to_csv("trending_movies.csv", index=False)

Page 1 completed | Total rows: 20
Page 2 completed | Total rows: 40
Page 3 completed | Total rows: 60
Page 4 completed | Total rows: 80
Page 5 completed | Total rows: 100
Page 6 completed | Total rows: 120
Page 7 completed | Total rows: 140
Page 8 completed | Total rows: 160
Page 9 completed | Total rows: 180
Page 10 completed | Total rows: 200
Page 11 completed | Total rows: 220
Page 12 completed | Total rows: 240
Page 13 completed | Total rows: 260
Page 14 completed | Total rows: 280
Page 15 completed | Total rows: 300
Page 16 completed | Total rows: 320
Page 17 completed | Total rows: 340
Page 18 completed | Total rows: 360
Page 19 completed | Total rows: 380
Page 20 completed | Total rows: 400
Page 21 completed | Total rows: 420
Page 22 completed | Total rows: 440
Page 23 completed | Total rows: 460
Page 24 completed | Total rows: 480
Page 25 completed | Total rows: 500
Page 26 completed | Total rows: 520
Page 27 completed | Total rows: 540
Page 28 completed | Total rows: 560
Page 29 completed | Total rows: 580
Page 30 completed | Total rows: 600
Page 31 completed | Total rows: 620
Page 32 completed | Total rows: 640
Page 33 completed | Total rows: 660
Page 34 completed | Total rows: 680
Page 35 completed | Total rows: 700
Page 36 completed | Total rows: 720
Page 37 completed | Total rows: 740
Page 38 completed | Total rows: 760
Page 39 completed | Total rows: 780
Page 40 completed | Total rows: 800
Page 41 completed | Total rows: 820
Page 42 completed | Total rows: 840
Page 43 completed | Total rows: 860
Page 44 completed | Total rows: 880
Page 45 completed | Total rows: 900
Page 46 completed | Total rows: 920
Page 47 completed | Total rows: 940
Page 48 completed | Total rows: 960
Page 49 completed | Total rows: 980
Page 50 completed | Total rows: 1000
Page 51 completed | Total rows: 1020
Page 52 completed | Total rows: 1040
Page 53 completed | Total rows: 1060
Page 54 completed | Total rows: 1080
Page 55 completed | Total rows: 1100
Page 56 completed | Total rows: 1120
Page 57 completed | Total rows: 1140
Page 58 completed | Total rows: 1160
Page 59 completed | Total rows: 1180
Page 60 completed | Total rows: 1200
Page 61 completed | Total rows: 1220
Page 62 completed | Total rows: 1240
Page 63 completed | Total rows: 1260
Page 64 completed | Total rows: 1280
Page 65 completed | Total rows: 1300
Page 66 completed | Total rows: 1320
Page 67 completed | Total rows: 1340
Page 68 completed | Total rows: 1360
Page 69 completed | Total rows: 1380
Page 70 completed | Total rows: 1400
Page 71 completed | Total rows: 1420
Page 72 completed | Total rows: 1440
Page 73 completed | Total rows: 1460
Page 74 completed | Total rows: 1480
Page 75 completed | Total rows: 1500
Page 76 completed | Total rows: 1520
Page 77 completed | Total rows: 1540
Page 78 completed | Total rows: 1560
Page 79 completed | Total rows: 1580
Page 80 completed | Total rows: 1600
Page 81 completed | Total rows: 1620
Page 82 completed | Total rows: 1640
Page 83 completed | Total rows: 1660
Page 84 completed | Total rows: 1680
Page 85 completed | Total rows: 1700
Page 86 completed | Total rows: 1720
Page 87 completed | Total rows: 1740
Page 88 completed | Total rows: 1760
Page 89 completed | Total rows: 1780
Page 90 completed | Total rows: 1800
Page 91 completed | Total rows: 1820
Page 92 completed | Total rows: 1840
Page 93 completed | Total rows: 1860
Page 94 completed | Total rows: 1880
Page 95 completed | Total rows: 1900
Page 96 completed | Total rows: 1920
Page 97 completed | Total rows: 1940
Page 98 completed | Total rows: 1960
Page 99 completed | Total rows: 1980
Page 100 completed | Total rows: 1999
Page 101 completed | Total rows: 2019
Page 102 completed | Total rows: 2039
Page 103 completed | Total rows: 2059
Page 104 completed | Total rows: 2079
Page 105 completed | Total rows: 2099
Page 106 completed | Total rows: 2119
Page 107 completed | Total rows: 2139
Page 108 completed | Total rows: 2159
Page 109 completed | Total rows: 2179
Page 110 completed | Total rows: 2199
Page 111 completed | Total rows: 2219
Page 112 completed | Total rows: 2239
Page 113 completed | Total rows: 2259
Page 114 completed | Total rows: 2279
Page 115 completed | Total rows: 2299
Page 116 completed | Total rows: 2319
Page 117 completed | Total rows: 2339
Page 118 completed | Total rows: 2359
Page 119 completed | Total rows: 2379
Page 120 completed | Total rows: 2399
Page 121 completed | Total rows: 2419
Page 122 completed | Total rows: 2439
Page 123 completed | Total rows: 2459
Page 124 completed | Total rows: 2479
Page 125 completed | Total rows: 2499
Page 126 completed | Total rows: 2519
Page 127 completed | Total rows: 2539
Page 128 completed | Total rows: 2559
Page 129 completed | Total rows: 2579
Page 130 completed | Total rows: 2599
Page 131 completed | Total rows: 2619
Page 132 completed | Total rows: 2639
Page 133 completed | Total rows: 2659
Page 134 completed | Total rows: 2679
Page 135 completed | Total rows: 2699
Page 136 completed | Total rows: 2719
Page 137 completed | Total rows: 2739
Page 138 completed | Total rows: 2759
Page 139 completed | Total rows: 2779
Page 140 completed | Total rows: 2799
Page 141 completed | Total rows: 2819
Page 142 completed | Total rows: 2839
Page 143 completed | Total rows: 2859
Page 144 completed | Total rows: 2879
Page 145 completed | Total rows: 2899
Page 146 completed | Total rows: 2919
Page 147 completed | Total rows: 2939
Page 148 completed | Total rows: 2959
Page 149 completed | Total rows: 2979
Page 150 completed | Total rows: 2999
Page 151 completed | Total rows: 3019
Page 152 completed | Total rows: 3039
Page 153 completed | Total rows: 3059
Page 154 completed | Total rows: 3079
Page 155 completed | Total rows: 3099
Page 156 completed | Total rows: 3119
Page 157 completed | Total rows: 3139
Page 158 completed | Total rows: 3159
Page 159 completed | Total rows: 3179
Page 160 completed | Total rows: 3199
Page 161 completed | Total rows: 3219
Page 162 completed | Total rows: 3239
Page 163 completed | Total rows: 3259
Page 164 completed | Total rows: 3279
Page 165 completed | Total rows: 3299
Page 166 completed | Total rows: 3319
Page 167 completed | Total rows: 3339
Page 168 completed | Total rows: 3359
Page 169 completed | Total rows: 3379
Page 170 completed | Total rows: 3399
Page 171 completed | Total rows: 3419
Page 172 completed | Total rows: 3439
Page 173 completed | Total rows: 3459
Page 174 completed | Total rows: 3479
Page 175 completed | Total rows: 3498
Page 176 completed | Total rows: 3518
Page 177 completed | Total rows: 3538
Page 178 completed | Total rows: 3558
Page 179 completed | Total rows: 3578
Page 180 completed | Total rows: 3598
Page 181 completed | Total rows: 3618
Page 182 completed | Total rows: 3638
Page 183 completed | Total rows: 3658
Page 184 completed | Total rows: 3678
Page 185 completed | Total rows: 3698
Page 186 completed | Total rows: 3718
Page 187 completed | Total rows: 3738
Page 188 completed | Total rows: 3758
Page 189 completed | Total rows: 3778
Page 190 completed | Total rows: 3798
Page 191 completed | Total rows: 3818
Page 192 completed | Total rows: 3838
Page 193 completed | Total rows: 3858
Page 194 completed | Total rows: 3878
Page 195 completed | Total rows: 3898
Page 196 completed | Total rows: 3917
Page 197 completed | Total rows: 3937
Page 198 completed | Total rows: 3957
Page 199 completed | Total rows: 3977
Page 200 completed | Total rows: 3997
Page 201 completed | Total rows: 4016
Page 202 completed | Total rows: 4036
Page 203 completed | Total rows: 4056
Page 204 completed | Total rows: 4076
Page 205 completed | Total rows: 4096
Page 206 completed | Total rows: 4116
Page 207 completed | Total rows: 4136
Page 208 completed | Total rows: 4156
Page 209 completed | Total rows: 4176
Page 210 completed | Total rows: 4196
Page 211 completed | Total rows: 4216
Page 212 completed | Total rows: 4236
Page 213 completed | Total rows: 4256
Page 214 completed | Total rows: 4276
Page 215 completed | Total rows: 4296
Page 216 completed | Total rows: 4316
Page 217 completed | Total rows: 4336
Page 218 completed | Total rows: 4356
Page 219 completed | Total rows: 4376
Page 220 completed | Total rows: 4396
Page 221 completed | Total rows: 4416
Page 222 completed | Total rows: 4436
Page 223 completed | Total rows: 4456
Page 224 completed | Total rows: 4476
Page 225 completed | Total rows: 4496
Page 226 completed | Total rows: 4516
Page 227 completed | Total rows: 4536
Page 228 completed | Total rows: 4556
Page 229 completed | Total rows: 4576
Page 230 completed | Total rows: 4596
Page 231 completed | Total rows: 4616
Page 232 completed | Total rows: 4636
Page 233 completed | Total rows: 4656
Page 234 completed | Total rows: 4676
Page 235 completed | Total rows: 4696
Page 236 completed | Total rows: 4716
Page 237 completed | Total rows: 4735
Page 238 completed | Total rows: 4755
Page 239 completed | Total rows: 4775
Page 240 completed | Total rows: 4795
Page 241 completed | Total rows: 4815
Page 242 completed | Total rows: 4835
Page 243 completed | Total rows: 4855
Page 244 completed | Total rows: 4875
Page 245 completed | Total rows: 4895
Page 246 completed | Total rows: 4915
Page 247 completed | Total rows: 4935
Page 248 completed | Total rows: 4955
Page 249 completed | Total rows: 4975
Page 250 completed | Total rows: 4995
Page 251 completed | Total rows: 5015
Page 252 completed | Total rows: 5035
Page 253 completed | Total rows: 5055
Page 254 completed | Total rows: 5075
Page 255 completed | Total rows: 5095
Page 256 completed | Total rows: 5115
Page 257 completed | Total rows: 5135
Page 258 completed | Total rows: 5155
Page 259 completed | Total rows: 5175
Page 260 completed | Total rows: 5195
Page 261 completed | Total rows: 5215
Page 262 completed | Total rows: 5235
Page 263 completed | Total rows: 5255
Page 264 completed | Total rows: 5275
Page 265 completed | Total rows: 5295
Page 266 completed | Total rows: 5315
Page 267 completed | Total rows: 5335
Page 268 completed | Total rows: 5355
Page 269 completed | Total rows: 5375
Page 270 completed | Total rows: 5395
Page 271 completed | Total rows: 5415
Page 272 completed | Total rows: 5435
Page 273 completed | Total rows: 5455
Page 274 completed | Total rows: 5475
Page 275 completed | Total rows: 5495
Page 276 completed | Total rows: 5515
Page 277 completed | Total rows: 5535
Page 278 completed | Total rows: 5555
Page 279 completed | Total rows: 5575
Page 280 completed | Total rows: 5595
Page 281 completed | Total rows: 5613
Page 282 completed | Total rows: 5633
Page 283 completed | Total rows: 5653
Page 284 completed | Total rows: 5673
Page 285 completed | Total rows: 5693
Page 286 completed | Total rows: 5713
Page 287 completed | Total rows: 5733
Page 288 completed | Total rows: 5753
Page 289 completed | Total rows: 5773
Page 290 completed | Total rows: 5793
Page 291 completed | Total rows: 5813
Page 292 completed | Total rows: 5833
Page 293 completed | Total rows: 5853
Page 294 completed | Total rows: 5873
Page 295 completed | Total rows: 5893
Page 296 completed | Total rows: 5913
Page 297 completed | Total rows: 5933
Page 298 completed | Total rows: 5953
Page 299 completed | Total rows: 5973
Page 300 completed | Total rows: 5993
Page 301 completed | Total rows: 6013
Page 302 completed | Total rows: 6033
Page 303 completed | Total rows: 6053
Page 304 completed | Total rows: 6073
Page 305 completed | Total rows: 6093
Page 306 completed | Total rows: 6113
Page 307 completed | Total rows: 6133
Page 308 completed | Total rows: 6153
Page 309 completed | Total rows: 6173
Page 310 completed | Total rows: 6193
Page 311 completed | Total rows: 6211
Page 312 completed | Total rows: 6231
Page 313 completed | Total rows: 6251
Page 314 completed | Total rows: 6271
Page 315 completed | Total rows: 6291
Page 316 completed | Total rows: 6309
Page 317 completed | Total rows: 6329
Page 318 completed | Total rows: 6349
Page 319 completed | Total rows: 6369
Page 320 completed | Total rows: 6389
Page 321 completed | Total rows: 6409
Page 322 completed | Total rows: 6429
Page 323 completed | Total rows: 6449
Page 324 completed | Total rows: 6469
Page 325 completed | Total rows: 6489
Page 326 completed | Total rows: 6509
Page 327 completed | Total rows: 6529
Page 328 completed | Total rows: 6549
Page 329 completed | Total rows: 6569
Page 330 completed | Total rows: 6589
Page 331 completed | Total rows: 6609
Page 332 completed | Total rows: 6629
Page 333 completed | Total rows: 6649
Page 334 completed | Total rows: 6669
Page 335 completed | Total rows: 6689
Page 336 completed | Total rows: 6709
Page 337 completed | Total rows: 6729
Page 338 completed | Total rows: 6749
Page 339 completed | Total rows: 6769
Page 340 completed | Total rows: 6789
Page 341 completed | Total rows: 6809
Page 342 completed | Total rows: 6829
Page 343 completed | Total rows: 6849
Page 344 completed | Total rows: 6869
Page 345 completed | Total rows: 6889
Page 346 completed | Total rows: 6909
Page 347 completed | Total rows: 6929
Page 348 completed | Total rows: 6949
Page 349 completed | Total rows: 6969
Page 350 completed | Total rows: 6989
Page 351 completed | Total rows: 7009
Page 352 completed | Total rows: 7029
Page 353 completed | Total rows: 7049
Page 354 completed | Total rows: 7069
Page 355 completed | Total rows: 7089
Page 356 completed | Total rows: 7109
Page 357 completed | Total rows: 7129
Page 358 completed | Total rows: 7149
Page 359 completed | Total rows: 7169
Page 360 completed | Total rows: 7189
Page 361 completed | Total rows: 7209
Page 362 completed | Total rows: 7229
Page 363 completed | Total rows: 7249
Page 364 completed | Total rows: 7269
Page 365 completed | Total rows: 7289
Page 366 completed | Total rows: 7309
Page 367 completed | Total rows: 7329
Page 368 completed | Total rows: 7349
Page 369 completed | Total rows: 7369
Page 370 completed | Total rows: 7389
Page 371 completed | Total rows: 7409
Page 372 completed | Total rows: 7429
Page 373 completed | Total rows: 7449
Page 374 completed | Total rows: 7469
Page 375 completed | Total rows: 7489
Page 376 completed | Total rows: 7509
Page 377 completed | Total rows: 7529
Page 378 completed | Total rows: 7549
Page 379 completed | Total rows: 7569
Page 380 completed | Total rows: 7589
Page 381 completed | Total rows: 7609
Page 382 completed | Total rows: 7629
Page 383 completed | Total rows: 7649
Page 384 completed | Total rows: 7669
Page 385 completed | Total rows: 7689
Page 386 completed | Total rows: 7709
Page 387 completed | Total rows: 7729
Page 388 completed | Total rows: 7749
Page 389 completed | Total rows: 7769
Page 390 completed | Total rows: 7789
Page 391 completed | Total rows: 7809
Page 392 completed | Total rows: 7829
Page 393 completed | Total rows: 7849
Page 394 completed | Total rows: 7869
Page 395 completed | Total rows: 7889
Page 396 completed | Total rows: 7909
Page 397 completed | Total rows: 7929
Page 398 completed | Total rows: 7949
Page 399 completed | Total rows: 7969
Page 400 completed | Total rows: 7989
Page 401 completed | Total rows: 8009
Page 402 completed | Total rows: 8029
Page 403 completed | Total rows: 8049
Page 404 completed | Total rows: 8069
Page 405 completed | Total rows: 8089
Page 406 completed | Total rows: 8109
Page 407 completed | Total rows: 8129
Page 408 completed | Total rows: 8149
Page 409 completed | Total rows: 8169
Page 410 completed | Total rows: 8189
Page 411 completed | Total rows: 8209
Page 412 completed | Total rows: 8229
Page 413 completed | Total rows: 8249
Page 414 completed | Total rows: 8269
Page 415 completed | Total rows: 8289
Page 416 completed | Total rows: 8309
Page 417 completed | Total rows: 8329
Page 418 completed | Total rows: 8349
Page 419 completed | Total rows: 8369
Page 420 completed | Total rows: 8389
Page 421 completed | Total rows: 8409
Page 422 completed | Total rows: 8429
Page 423 completed | Total rows: 8449
Page 424 completed | Total rows: 8469
Page 425 completed | Total rows: 8489
Page 426 completed | Total rows: 8509
Page 427 completed | Total rows: 8529
Page 428 completed | Total rows: 8549
Page 429 completed | Total rows: 8569
Page 430 completed | Total rows: 8589
Page 431 completed | Total rows: 8609
Page 432 completed | Total rows: 8629
Page 433 completed | Total rows: 8649
Page 434 completed | Total rows: 8669
Page 435 completed | Total rows: 8689
Page 436 completed | Total rows: 8709
Page 437 completed | Total rows: 8729
Page 438 completed | Total rows: 8749
Page 439 completed | Total rows: 8769
Page 440 completed | Total rows: 8789
Page 441 completed | Total rows: 8809
Page 442 completed | Total rows: 8829
Page 443 completed | Total rows: 8849
Page 444 completed | Total rows: 8869
Page 445 completed | Total rows: 8889
Page 446 completed | Total rows: 8909
Page 447 completed | Total rows: 8929
Page 448 completed | Total rows: 8949
Page 449 completed | Total rows: 8969
Page 450 completed | Total rows: 8989
Page 451 completed | Total rows: 9009
Page 452 completed | Total rows: 9029
Page 453 completed | Total rows: 9049
Page 454 completed | Total rows: 9069
Page 455 completed | Total rows: 9089
Page 456 completed | Total rows: 9109
Page 457 completed | Total rows: 9129
Page 458 completed | Total rows: 9149
Page 459 completed | Total rows: 9169
Page 460 completed | Total rows: 9189
Page 461 completed | Total rows: 9209
Page 462 completed | Total rows: 9229
Page 463 completed | Total rows: 9249
Page 464 completed | Total rows: 9269
Page 465 completed | Total rows: 9289
Page 466 completed | Total rows: 9309
Page 467 completed | Total rows: 9329
Page 468 completed | Total rows: 9349
Page 469 completed | Total rows: 9369
Page 470 completed | Total rows: 9389
Page 471 completed | Total rows: 9409
Page 472 completed | Total rows: 9429
Page 473 completed | Total rows: 9449
Page 474 completed | Total rows: 9469
Page 475 completed | Total rows: 9489
Page 476 completed | Total rows: 9509
Page 477 completed | Total rows: 9529
Page 478 completed | Total rows: 9549
Page 479 completed | Total rows: 9569
Page 480 completed | Total rows: 9589
Page 481 completed | Total rows: 9609
Page 482 completed | Total rows: 9629
Page 483 completed | Total rows: 9649
Page 484 completed | Total rows: 9669
Page 485 completed | Total rows: 9689
Page 486 completed | Total rows: 9709
Page 487 completed | Total rows: 9729
Page 488 completed | Total rows: 9749
Page 489 completed | Total rows: 9769
Page 490 completed | Total rows: 9789
Page 491 completed | Total rows: 9809
Page 492 completed | Total rows: 9829
Page 493 completed | Total rows: 9849
Page 494 completed | Total rows: 9869
Page 495 completed | Total rows: 9889
Page 496 completed | Total rows: 9909
Page 497 completed | Total rows: 9929
Page 498 completed | Total rows: 9949
Page 499 completed | Total rows: 9969
Page 500 completed | Total rows: 9989
(9989, 16)
   adult                     backdrop_path       id              title  \
0  False  /wE6syT1vv6W24iLGfhR4kQHnIDN.jpg  1302904  Practical Magic 2
1  False  /ujUwzNV8ZkOzZonvhhHsc9KOKDf.jpg  1058424               Hope
2  False  /ytoLEl5yDaxB8AtZ52uKWjaQ9ql.jpg  1514026              Buddy
3  False  /tzoarEu7TsG959upiELyYPm5kO9.jpg  1236045            Animals
4  False  /zDE9hd1SG9695YncbZGjSf7Z9Jk.jpg  1153576     Street Fighter

      original_title                                           overview  \
0  Practical Magic 2  The Owens sisters must confront the dark curse...
1                 호프  In the remote South Korean village of Hope Har...
2              Buddy  A magical, singing orange unicorn holds his ca...
3            Animals  When the son of an L.A. mayoral candidate is k...
4     Street Fighter  In 1993, estranged Street Fighters Ryu and Ken...

                        poster_path media_type original_language  \
0  /ogwQOLbCfncjvBhFb5l0OmQH8KC.jpg      movie                en
1  /1n37BJchWHLiSYQkuFxe5KjB951.jpg      movie                ko
2  /1BdZbNvl1SfrrX8J9X5tQzN6Ivu.jpg      movie                en

In [17]:
final_data

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count
0,False,/wE6syT1vv6W24iLGfhR4kQHnIDN.jpg,1302904,Practical Magic 2,Practical Magic 2,The Owens sisters must confront the dark curse...,/ogwQOLbCfncjvBhFb5l0OmQH8KC.jpg,movie,en,"[10749, 14, 35]",89.1126,2026-09-09,False,False,6.286,131
1,False,/ujUwzNV8ZkOzZonvhhHsc9KOKDf.jpg,1058424,Hope,호프,In the remote South Korean village of Hope Har...,/1n37BJchWHLiSYQkuFxe5KjB951.jpg,movie,ko,"[878, 9648, 28]",42.2970,2026-07-15,False,False,7.300,127
2,False,/ytoLEl5yDaxB8AtZ52uKWjaQ9ql.jpg,1514026,Buddy,Buddy,"A magical, singing orange unicorn holds his ca...",/1BdZbNvl1SfrrX8J9X5tQzN6Ivu.jpg,movie,en,"[27, 35, 14]",14.7618,2026-08-27,False,False,7.821,81
3,False,/tzoarEu7TsG959upiELyYPm5kO9.jpg,1236045,Animals,Animals,When the son of an L.A. mayoral candidate is k...,/iISM36voS1E8gX9BM0DVK0kgi3E.jpg,movie,en,"[53, 18]",260.5060,2026-10-09,False,False,7.400,305
4,False,/zDE9hd1SG9695YncbZGjSf7Z9Jk.jpg,1153576,Street Fighter,Street Fighter,"In 1993, estranged Street Fighters Ryu and Ken...",/dJPT2Uf12X6aFg8i5N67NTpIZ9t.jpg,movie,en,"[28, 14]",41.0928,2026-10-13,False,False,6.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9984,False,/e01eWKavuZe0Es2l62jE9MgnRa.jpg,1173003,Kaytek the Wizard,Kajtek czarodziej,"Kaytek, an unusually stubborn twelve-year-old,...",/myjfd71rUywXTp1YuCRKtHhipca.jpg,movie,pl,"[10751, 14, 12]",1.0098,2023-11-03,False,False,5.100,6
9985,False,/z3zeYgp8P8SqTypwatOHINDCnHM.jpg,1171634,When Fall Is Coming,Quand vient l'automne,Michelle is enjoying a peaceful retirement in ...,/pazjzgxyrDFIwe3xFJ4KyFJCd77.jpg,movie,fr,"[18, 53, 35]",3.7178,2024-10-02,False,False,6.603,258
9986,False,/swuTyjZeqYJMc5Fejg8UX1ObGJ5.jpg,1170367,Can You See Us?,Can You See Us?,"Rejected by his father at birth, a boy with al...",/yGxMFN4AArZ7PnB5plM90zcaF2i.jpg,movie,en,[18],0.9056,2023-02-27,False,False,7.100,5
9987,False,/dx3w4VtCdpEBcQkjq2DrTfhlULX.jpg,1167490,Takano Tofu,高野豆腐店の春,Tatsuo and his daughter Haru run Takano Tofu S...,/okYgaytwvw6iGGIoItUPupNUcvT.jpg,movie,ja,"[10751, 18]",1.1516,2023-08-23,False,False,6.900,16
9988,False,NaN,1167419,Alien Attack at Groom Lake,Alien Attack at Groom Lake,The Widower of a decorated military sniper liv...,/7O0hVqFQX0Rx3sJwJ3ovThRoEY5.jpg,movie,en,"[878, 53]",1.1495,2024-01-02,False,False,10.000,1